# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Andrew Weaver's Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "privatezero.github.io/blog" # the subpath of your site, e.g. /blog
url: "privatezero.github.io" # the base hostname & protocol for your site
# twitter_username: private_zero
# github_username:  privatezero

# Build settings
markdown: kramdown
# theme: jekyll-hilmi

# Theme setting
author: Andrew Weaver
nick:   Weaver
profession: "Archivist and Librarian"
tagline: "Audio//Visual//Digital"
timezone: Pacific
baseurl: ""
feed: true

# Social links
twitter: private_zero
github: privatezero
